hydra:
  run:
    dir: ./experiments/${name}/${hydra.job.override_dirname}/seed=${seed}
  sweep:
    dir: ./experiments/${name}/${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        item_sep: '_'
        exclude_keys:
          - seed
          - name

defaults:
  - launcher: slurm
  - inference_algo: lmh
  - override hydra/launcher: submitit_slurm

name: test_baselines
seed: 0