hydra:
  run:
    dir: ./experiments/${name}/${hydra.job.override_dirname}/seed=${seed}
  sweep:
    dir: ./experiments/${name}/${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        item_sep: '_'
        exclude_keys:
          - seed
          - name

defaults:
  # - launcher: slurm
  - inference_algo: bbvi
  # - override hydra/launcher: submitit_slurm

name: test_gmm_baselines
seed: 42
data_file: finite_gmm_data_n=1000_mean_dim=2.npz
validation_data_file: finite_gmm_data_n=500_mean_dim=2_validation.npz
dim: 2